using System;
using System.Collections.Generic;

namespace RO.DevTest.Application.Features.Sale.Queries.GetSalesAnalysisQuery;

/// <summary>
/// View model for sales analysis results
/// </summary>
public class SalesAnalysisVm
{
    /// <summary>
    /// Start date of the analysis period
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// End date of the analysis period
    /// </summary>
    public DateTime EndDate { get; set; }

    /// <summary>
    /// Total number of sales in the period
    /// </summary>
    public int TotalSales { get; set; }

    /// <summary>
    /// Total revenue generated in the period
    /// </summary>
    public decimal TotalRevenue { get; set; }

    /// <summary>
    /// Revenue breakdown by product
    /// </summary>
    public List<ProductRevenueDto> ProductRevenues { get; set; } = new List<ProductRevenueDto>();
}

/// <summary>
/// Data transfer object for product revenue information
/// </summary>
public class ProductRevenueDto
{
    /// <summary>
    /// Unique identifier of the product
    /// </summary>
    public Guid ProductId { get; set; }

    /// <summary>
    /// Name of the product
    /// </summary>
    public string ProductName { get; set; } = string.Empty;

    /// <summary>
    /// Total quantity sold in the period
    /// </summary>
    public int Quantity { get; set; }

    /// <summary>
    /// Total revenue generated by this product in the period
    /// </summary>
    public decimal Revenue { get; set; }

    /// <summary>
    /// Percentage of total revenue contributed by this product
    /// </summary>
    public decimal PercentageOfTotalRevenue { get; set; }
}
